coslr: true
criterions:
  PerformanceLoss:
    def_file: ./loss/SoftmaxLoss.py
    loss_params: {}
    optim_params: null
    weight: 1.0
endlr: 0.0
last: false
memory: {centroids: false, init_centroids: false}
model_dir: null
networks:
  classifier:
    def_file: ./models/DotProductClassifier.py
    optim_params: {lr: 0.2, momentum: 0.9, weight_decay: 0.0005}
    params: {dataset: ImageNet_LT, feat_dim: 512, log_dir: ./logs/ImageNet_LT_90subset/models/resnext18_no_synth,
      num_classes: 1000, stage1_weights: false}
  feat_model:
    def_file: ./models/ResNext18Feature.py
    fix: false
    optim_params: {lr: 0.2, momentum: 0.9, weight_decay: 0.0005}
    params: {dataset: ImageNet_LT, dropout: null, log_dir: ./logs/ImageNet_LT_90subset/models/resnext18_no_synth,
      stage1_weights: false, use_fc: false, use_selfatt: false}
shuffle: false
training_opt:
  backbone: resnext18
  batch_size: 512
  dataset: ImageNet_LT
  subset: 90
  # synth_data: true
  # synth_root: /mnt/zhang-nas/jiahuic/synth_LT_data/ImageNetLT/rand_img_cond  # MIDI 
  # synth_root: /datastor1/jiahuikchen/synth_ImageNet/rand_img_cond # A40
  display_step: 10
  feature_dim: 512 # ResNext18 
  # 2048 # ResNext50 
  log_dir: ./logs/ImageNet_LT_90subset/models/resnext18_no_synth
  log_root: /logs/ImageNet_LT_90subset
  num_classes: 1000
  num_epochs: 150
  num_workers: 4 
  open_threshold: 0.1
  sampler: null
  scheduler_params: {gamma: 0.1, step_size: 30}
  stage: resnext18_rand_img_cond
  sub_dir: models
